### PR TITLE
Slack notification config

### PR DESCRIPTION
**Pull request by jespino**

### CODE REVIEW

**Comment by superalex** [comment]
@jespino shouldn't this PR include updating the plugin version?

**Comment by jespino** [comment]
@superalex nop, the current published version is the 0.0.8, then when we publish the next one, will be the 0.0.9, which is the version for the python package.

The version in package.json is 0.0.9, from some commits ago.

Anyway the increment of version must be done in the muster branch IMHO. You can merge it, and release a new 0.1.0 or 0.0.10 version in both, back and front.

**Comment by bameda** [comment]
Be careful with the releasing and the compatibility with taiga-back/front versions. I would wait until the new version of taiga to get a new one.

**Comment by superalex** [comment]
Ok!, thank you! ;)

**Comment by superalex** [comment]
Great! :+1:

**Pull request merged**
